
public class GameProcessor {
	
	public char[][] getGraphicsMap() {
		return new char[][]{
			{Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,},
			{Legend.BLANK_SPACE,Legend.YOU,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,},
			{Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.MHO,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,},
			{Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,},
			{Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,},
			{Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,},
			{Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,},
			{Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,},
			{Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,},
			{Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,},
			{Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,},
			{Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,Legend.BLANK_SPACE,}
		};
	}
	
}
